name: Upload LambdaFX Output IaC Yaml to S3

on:
  # Execute action when master branch has a new release
  push:
    branches: [ "master" ]
    paths:
      - 'cloudformation/ODF-LambdaFX-Output-Template.yaml'
      
  workflow_dispatch:  # Enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267287442:role/GithubUpdateIaC_OutputLambdaFX
          aws-region: us-west-2

      - name: Delete old version of LambdaFX .yaml from S3
        run: aws s3 rm s3://fakequakes-iac-code/ODF-LambdaFX-Output-Template.yaml

      - name: Upload new LambdaFX .yaml to S3
        run: aws s3 cp cloudformation/ODF-LambdaFX-Output-Template.yaml s3://fakequakes-iac-code/ODF-LambdaFX-Output-Template.yaml

      - name: Trigger GitHub action to Update ODF Stack
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CICD_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/UO-Geophysics/on_demand_fakequakes/dispatches \
          -d '{"event_type":"stack-build","client_payload":{"unit":false,"integration":true}}'
